# Generated by Django 5.2.5 on 2025-09-01 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_49578b_idx'), models.Index(fields=['is_active'], name='ip_tracking_is_acti_f8fe49_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('path', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('method', models.CharField(default='GET', max_length=10)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_3489f7_idx'), models.Index(fields=['timestamp'], name='ip_tracking_timesta_b1bb90_idx'), models.Index(fields=['path'], name='ip_tracking_path_65894f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.TextField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_count', models.IntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_11f206_idx'), models.Index(fields=['detected_at'], name='ip_tracking_detecte_a07ef7_idx'), models.Index(fields=['is_resolved'], name='ip_tracking_is_reso_ccfb1f_idx')],
            },
        ),
    ]
